### ISSUE TITLE
Running notebook w/ python 3

### ISSUE THREAD

**Issue by henrymj** [vsoch/forward#33]
Hello! I wrote a notebook on my local in python 3 and want to run it on Sherlock. Once running the notebook in Sherlock, I don't see a way to change the kernel (I tried `ml python=3.6.1`, but it did not work). What do you suggest? Thank you in advance!

**Comment by vsoch** [comment]
I’m on East Coast time so I’m off to bed, but if you can share the commands you’ve tried so far I can give you a script to try early tomorrow.

**Comment by vsoch** [comment]
Oh! And in case you weren’t aware, we also can offer Sherlock on demand https://www.sherlock.stanford.edu/docs/user-guide/ondemand/

**Comment by henrymj** [comment]
I've only tried loading the python3 module, and then running bash start.sh jupyter, but it hasn't been successful so far. Thank you for your help & go to sleep!

**Comment by vsoch** [comment]
okay here is what I just did. First I logged in with `ssh sherlock` (after setup of my ~/.ssh/config based on the instructions in this repository). This is to ensure that we can communicate cleanly.

```bash
ssh sherlock
```
Once that worked, I checked the latest version of Python on sherlock, which is `python/3.6.1` (as a module). The version of jupyter hasn't changed either `py-jupyter/1.0.0_py36`.

So - we already have a script setup for that, I ran this:

```bash
$ bash start.sh sherlock/py3-jupyter 
```
And everything seemed ok - logs don't have any errors, but I think the admins on Sherlock (mainly Kilian) must have disabled this ability because I get a connection refused. I tried the same workflow with VPN, same response. Everyone is sleeping over there in CA but I'll check in with them and ping you with an update here with anything I learn. Unfortunately sometimes security standards get hardened so you can no longer use simple tools like forward :/

In the meantime, check out Sherlock On Demand, minimally I think you can request a notebook.

**Comment by henrymj** [comment]
Thank you! I must have missed that in the documentation. I've been able to use forward with the original jupyter command, so hopefully i will be able to use this one as well.

**Comment by vsoch** [comment]
Fantastic! Fingers crossed that it works ok - my issue might have been that I’m off campus.

**Comment by vsoch** [comment]
Did you get it working @henrymj? Can we close the issue?

**Comment by henrymj** [comment]
Yes! Sorry for my delay - the command worked excellently.

**Comment by henrymj** [comment]
Hi, 

I'm now running into a related issue. Though the notebook is running a python 3 kernel, we are struggling to use pydeface (via subprocess.call). It seems like we can't load python/3.6.1 to the compute node that the notebook is running on, which we need for pydeface to work. 

We tried logging onto the compute node and loading python3 using `ml python/3.6.1`, but it did not change the results of `python --version`. Do you have any suggested work arounds?

Thank you!

**Comment by vsoch** [comment]
This particular script already has that module loaded. Take a look at the file to see. If you want to load other modules, edit the file.

**Comment by henrymj** [comment]
I see that - I guess I am confused why the jupyter terminal that I open in the compute node still says I am running python 2.7.5 when I try `python --version`

**Comment by vsoch** [comment]
python on sherlock is either python (2) or python3 (python 3) so you'd want to do `python3 --version`.

**Comment by vsoch** [comment]
@henrymj the module to load Jupyter (at least when I tested a long time ago!) _should_ load python again (3), which is why the script does this:

```
module load py-jupyter/1.0.0_py36
jupyter notebook --no-browser --port=$PORT
```
but if it's the case that it's not loading python3, could you please try adding the ml python command to that script and try again?

I suspect if you are using subprocess you just need to target python3 instead of python though.

**Comment by henrymj** [comment]
Thank you, I will try that tomorrow and update you asap.

**Comment by vsoch** [comment]
okay sounds good! It might be helpful to login to an interactive node, and then load the jupyter module manually and check the python versions you have on your path. It could be that you have another loaded. Afaik jupyter should detect the kernels available but maybe that's not the case. Let me know what you learn! I can try to help more after that.

**Comment by vsoch** [comment]
hey @henrymj a quick question for you - are you using the version before or after this commit? https://github.com/vsoch/forward/pull/32/files (e.g., look at the ssh config generation and see if it uses a hash or not). We are having users report issues with the ssh forward and I want to figure out if this change did it. Thanks!

**Comment by henrymj** [comment]
Mine seems to be the newer version with %C ! I hope this is helpful

**Comment by vsoch** [comment]
yes thank you! And this is what you see in your ~/.ssh/config as well? (e.g., you could have generated it before pulling to get the updated version, which wouldn't touch your original generation).

**Comment by henrymj** [comment]
Yes, that is what I see in my config!

**Comment by neutrinonerd3333** [comment]
Following this issue as author of #32 — curious what issues that PR may have caused!

**Comment by vsoch** [comment]
@neutrinonerd3333, @henrymj reports that it worked previously with the change, so that suggests that it isn't it? But you never know...

**Comment by henrymj** [comment]
Hi @vsoch, we weren't able to solve the issue, but have created a work around - finding when to run a separate pydeface.sh script. I think I will close the issue - it seems to be an issue separate from the jupyter notebook, which is working great!
