### ISSUE TITLE
Allow for hosts other than sherlock

### ISSUE THREAD

**Issue by raphtown** [vsoch/forward#9]
The proposed addition of the hosts directory in #8 is making me think we could pretty straightforwardly add the ability to use hosts other than sherlock.  This would make this utility applicable to any cluster using the SLURM scheduler.

**Comment by vsoch** [comment]
exactly! The user can choose his / her host based on generating configurations from scripts in the "hosts" folder. Within Stanford, we can have the naming schema like `sherlock_ssh.sh` and of course if a user extends it beyond Stanford, it would be `stanford_sherlock_ssh.sh`

We would need to equivalently provide the actual batches to be associated with particular configs, because not every host has the same modules to load, for example.

**Comment by vsoch** [comment]
This is good, we have farmshare and (moving forward) can add hosts per user request.
